package api

const (
	STATUS_SCHED_INIT      = 1001 // 指令初始化
	STATUS_SCHED_SENT      = 1002 // 指令已发送
	STATUS_SCHED_CMD_ACKED = 1003 // 指令已收回执
	STATUS_SCHED_PRE_ACKED = 1004 // 准备动作完成
	STATUS_SCHED_HEARTBEAT = 1005 // 运行状态的心跳
	STATUS_SCHED_END       = 1099 // 整个声明周期已结束
)

const (
	RESULT_SCHED_OK                 = 0
	RESULT_SCHED_LOCAL_FAIL         = 1011
	RESULT_SCHED_REMOTE_REJECTs     = 1021
	RESULT_SCHED_KILLED_ACK_TIMEOUT = 1031
	RESULT_SCHED_KILLED_PRE_TIMEOUT = 1031
	RESULT_SCHED_KILLED_HB_TIMEOUT  = 1041
	RESULT_SCHED_KILLED_RUN_TIMEOUT = 1051

	RESULT_SCHED_REVOKE = 1099
)

const (
	INT_ENABLED  = 1
	INT_DISABLED = 0
)

const (
	INT_INVALID = -1
	STR_INVALID = "none"
)
